# Generated by Django 5.1.2 on 2024-11-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='last_activity',
        ),
    ]
