# Generated by Django 5.1.2 on 2024-11-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_answervote_created_at_questionvote_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_name_case_insensitive',
        ),
    ]
