# Generated by Django 4.2.17 on 2024-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_tag_unique_tag_name_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
